### ISSUE TITLE
fix(flex-cn-setup): passing unquoted keys value causes chart failure

### ISSUE THREAD

**Issue by moabu** [GluuFederation/flex#618]
Hello Gluu/Jans team,
## Expected behavior

Create an environment variable with values boolean false ou string "false", to pass to micro-service persistence-loader.

## Actual behavior

The following helm values for an global environment variable generate a similar configmap bellow:

```
global:
  usrEnvs:
    normal:
      POTATO: false
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: eraseme
  namespace: default
data:
  POTATO: false # &lt;-- literal with boolean without quotes.
```

Resulting on error:

```
$ kubectl apply -f /tmp/potato.yaml 
Error from server (BadRequest): error when creating "/tmp/potato.yaml": ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal bool into Go struct field ConfigMap.data of type string
```

The expected behavior is:

```
kubectl --namespace default create configmap ereseme --from-literal=potato=false --dry-run -o yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ereseme
  namespace: default
data:
  potato: "false" # &lt;-- literal with with quotes.
```

#### Solution

All global envs should be quoted
